In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as start 

In [2]:
df=sns.load_dataset("titanic")

In [3]:
df["age"].isnull().sum()

177

In [4]:
pop=df["age"].dropna()

In [5]:
pop.isnull().sum()

0

Let suppose we have taken 25 sample from the population

In [6]:
sample=pop.sample(25).values

In [7]:
sample

array([29. , 40. , 36. , 27. , 22. , 18. , 21. , 23. , 26. , 28. , 45. ,
       48. , 19. , 26. , 47. , 33. , 22. , 19. , 23. , 39. ,  4. , 22. ,
       26. , 32.5, 23. ])

Now we have to test the assumptions

In [8]:
#Checking for the normality
from scipy.stats import shapiro

In [9]:
result=shapiro(sample)
p_values=result[1]
if p_values>0.05:
    print("Our Sample is normally distributed.")
else:
    print("Our Sample isn't normally distributed")

Our Sample is normally distributed.


In [10]:
pop_mean=35

In [11]:
from scipy.stats import ttest_1samp

In [12]:
result=ttest_1samp(sample,pop_mean)
p_value=result[1]/2 #as it is left-tailed test
if p_value>0.05:
    print("Our null hypothesis is true.Average age of the passenger is 35 year")
else:
    print("We reject our null hyopthesis and Average age is less than 35 year")

We reject our null hyopthesis and Average age is less than 35 year


In [13]:
result

TtestResult(statistic=-3.453048732255816, pvalue=0.0020689121790130813, df=24)

In [14]:
#Checking our test with the population dataset
df["age"].mean()

29.69911764705882

# Independent 2 Sample t-test:

Now we are claiming that the average age of male and average age for female would be similar for this we are going to do the t-test.

# Answer

Null Hypothesis(Ho):Average age of male is similar to the average age of female 
    
Alernative Hypothesis(Ha):Average age of male is not similar to avaerage age of Female. there is significant difference between them.

In [15]:
male_age=df[df["sex"]=='male']["age"]
female_age=df[df["sex"]=='female']["age"]

In [16]:
pop_male_age=male_age.dropna()
pop_female_age=female_age.dropna()

In [17]:
sample_male=pop_male_age.sample(25).values
sample_female=pop_female_age.sample(25).values

In [18]:
sample_male

array([36.  , 48.  , 50.  , 18.  , 30.  , 18.  , 14.  , 24.  , 33.  ,
       33.  , 33.  , 32.  , 32.  , 22.  , 26.  , 12.  , 40.  , 58.  ,
       22.  , 16.  , 20.  , 16.  , 19.  ,  0.67, 30.  ])

In [19]:
sample_female

array([34., 43., 14., 18., 22., 40.,  2., 24., 48., 18., 50., 36., 17.,
       29.,  2., 27., 21., 17., 18., 38., 24., 15., 24., 31., 25.])

# checking for assumptions

In [20]:
#normality check:

In [21]:
l={"sample_male":sample_male,"sample_female":sample_female}
for i in l:
    result=shapiro(l[i])
    p_value=result[1]
    if p_value>0.05:
        print(f"{i} is normally distributed")
    else:
        print(f"{i} isn't normally distributed")

sample_male is normally distributed
sample_female is normally distributed


In [22]:
#variance test

In [23]:
from scipy.stats import levene

result = levene(sample_male, sample_female)
if result[1] > 0.05:
    print("These two sample columns have equal variance")
else:
    print("Variance of these two columns are not equal")


These two sample columns have equal variance


# Testing the t-test:

In [24]:
from scipy.stats import ttest_ind

result = ttest_ind(sample_male, sample_female)
if result[1] > 0.05:
    print("We can't reject our null hypothesis, so the average age of males is similar to the average age of females.")
else:
    print("Average age of males is not similar to the average age of females. There is a significant difference.")


We can't reject our null hypothesis, so the average age of males is similar to the average age of females.


# Pair two sample t test :

Let's assume that a fitness center is evaluating the effectiveness of a new 8-week weight loss program.
They enroll 15 participants in the program and measure their weights before and after the program. The goal
is to test whether the new weight loss program leads to a significant reduction in the participants' weight.
Before the program: [80, 92, 75, 68, 85, 78, 73, 90, 70, 88, 76, 84, 82, 77, 91] After the program: [78, 93, 81,
67, 88, 76, 74, 91, 69, 88, 77, 81, 80, 79, 88] Significance level (α) = 0.05

# Answer :

so we have data of weight Before the program: [80, 92, 75, 68, 85, 78, 73, 90, 70, 88, 76, 84, 82, 77, 91]
and After the program: [78, 93, 81, 67, 88, 76, 74, 91, 69, 88, 77, 81, 80, 79, 88]
now our null hypothesis(Ho):mean(before)=mean(after)
alternative hypothesis(Ha):mean(before)>mean(after)

# now we need to test our assumptions :

In [25]:
# checking the normality of the different columns of these two columns
column_before=np.array([80, 92, 75, 68, 85, 78, 73, 90, 70, 88, 76, 84, 82, 77, 91])
column_after=np.array([78, 93, 81, 67, 88, 76, 74, 91, 69, 88, 77, 81, 80, 79, 88])

In [26]:
diff_column=column_before-column_after

In [27]:
diff_column

array([ 2, -1, -6,  1, -3,  2, -1, -1,  1,  0, -1,  3,  2, -2,  3])

In [28]:
result=shapiro(diff_column)
p_value=result[1]
if p_value>0.05:
     print("normally distributed")
else:
     print("not normally distreibuted")

normally distributed


Now we need to find out the t-statistic.

In [29]:
t_statistic=diff_column.mean()/(diff_column.std()/np.sqrt(15))

In [30]:
t_statistic

-0.10850778933039285

this the right-tailed test. now we need to find out the p_value with respect to t_statistic

In [31]:
from scipy.stats import t

p_value = t.sf(t_statistic, 14)


In [32]:
if p_value>0.05:
     print("we can't reject our null hypothesis and mean(before)=mean(after)")
else:
     print("we reject our null hypothesis and (Ha):mean(before)>mean(after)")

we can't reject our null hypothesis and mean(before)=mean(after)
